//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social_Network.DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialNetworkDatabaseContext : DbContext
    {
        public SocialNetworkDatabaseContext(string connectionString)
            : base(connectionString)
        {
        }
    
        public virtual DbSet<NetworkUsers> NetworkUsers { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<UserPhotos> UserPhotos { get; set; }
    }
}
